# Fundamentals of Machine Learning Lab

- M. Tech 1st Year
- Name: Kinjal Raykarmakar
- Roll No.: 24/IT/19

## Experiment 2

**OBJECTIVE:** To understand the NumPy functions

In [10]:
import numpy as np

---
(i) 1D array operations

In [11]:
# creating a 1D array
a = np.array([1,2,3,4,5,6])

# dimension
print("The dimensions of a are:", a.ndim)

# shape
print("The shape of a is:", a.shape)

# datatype
print("The dataype of a is:", a.dtype)

The dimensions of a are: 1
The shape of a is: (6,)
The dataype of a is: int64


---
(ii) 2D array operations

In [12]:
# creating a 2D array
b = np.array([[1,2,3], [4,5,6]])
print(b)

# reshape existing 1D array to 2D
bb = b.reshape((3,2))
print(bb)

# dimension and shape
print("Dimension of b is:", b.ndim)
print("Shape of b is:", b.shape)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
Dimension of b is: 2
Shape of b is: (2, 3)


---
(iii) Operations on NumPy arrays

In [13]:
# element wise multiplication
print(a)
print(a*3)

# element wise square
print("-------------------------")
print(a)
print(a**2)

# not an element wise multiplication
# just creates duplicate copies
print("-------------------------")
print([1,2,3]*2)

# modifying element through direct access
print("-------------------------")
print(a)
a[0] = 10
print(a)
print(bb)

[1 2 3 4 5 6]
[ 3  6  9 12 15 18]
-------------------------
[1 2 3 4 5 6]
[ 1  4  9 16 25 36]
-------------------------
[1, 2, 3, 1, 2, 3]
-------------------------
[1 2 3 4 5 6]
[10  2  3  4  5  6]
[[1 2]
 [3 4]
 [5 6]]


---
(iv) Create a numpy array copy

In [14]:
c = a.reshape(3,2).copy()
print(c)

# does not change a as it's a copy
c[0][0] = 99

print(c)
print(a)

[[10  2]
 [ 3  4]
 [ 5  6]]
[[99  2]
 [ 3  4]
 [ 5  6]]
[10  2  3  4  5  6]


---
(v) Indexing in NumPy Arrays

In [15]:
# printing a specific element
print(a[0])

# printing multiple elements in index 1 and 2
print(a[np.array([1,2])])

# printing elements in the array based on the passed condition
# here, even numbers are being printed
print("Even elements in a are:", a[a%2==0])

# assinging values to elements based on condition
a[a==10] = 12
print(a)

10
[2 3]
Even elements in a are: [10  2  4  6]
[12  2  3  4  5  6]


---
(vi) Clipping

In [16]:
# clipping allows us to modify the numpy array values that lie outside the range
# if the range is [3,5], then values lesser than 3 are made 3 and values greater than 5 are made 5
d = a.copy()
print(d)
print(d.clip(3,5))

[12  2  3  4  5  6]
[5 3 3 4 5 5]
